---
# This describes a basic build and deploy pipeline for the application.
# The default pipeline that would be created is not sufficient because the
# application depends on another project that does not currently have published
# maven artifacts.
#
# Some documentation can be found here:
# https://www.ng.bluemix.net/docs/manageapps/deployingapps.html#sharetextpipelines
#
# This support is currently described as "in development", so the YAML format
# could change at any time.  The easiest way to recreate this file is to create
# a pipeline and then append /yaml to the URL, as follows:
# GET <jazzhub url>/pipeline/user/project/yaml
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Changelog
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      # This script just dumps the changes included in this build into a file named changelog.txt
      # This change log can be used later to be included in notifications
      git log ${GIT_COMMIT}..HEAD --graph --oneline > changelog.txt
      cat changelog.txt
